-- 코드를 입력하세요
SELECT PATIENT.PT_NAME, PATIENT.PT_NO, PATIENT.GEND_CD, PATIENT.AGE, IFNULL(PATIENT.TLNO, "NONE")
FROM PATIENT
WHERE PATIENT.GEND_CD = 'W' AND PATIENT.AGE <= 12
ORDER BY PATIENT.AGE DESC, PATIENT.PT_NAME ASC