-- 코드를 입력하세요
SELECT MEMBER_PROFILE.MEMBER_ID, MEMBER_PROFILE.MEMBER_NAME, MEMBER_PROFILE.GENDER, DATE_FORMAT(MEMBER_PROFILE.DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MEMBER_PROFILE.GENDER = 'W' AND MONTH(MEMBER_PROFILE.DATE_OF_BIRTH) = '03' AND MEMBER_PROFILE.TLNO IS NOT NULL
ORDER BY MEMBER_PROFILE.MEMBER_ID ASC